name: "SWM GitHub Actions Basic"

# on: ["push", "pull-request"]
on:
  push:
    # 특정 브랜치에서 이벤트 발생시 actions 동작
    branches:
      - "main"
    # 특정 디렉토리에서 이벤트 발생시 actions 동작
    path:
      - "src/**"
      - "test/**"

jobs:
  first-job:
    name: "First Job"

  second-job:
    if: github.event == 'pull_request'
    name: "Second Job"

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        nodejs: ["16.x", "18.x"]

    # 각각의 matrix마다 job이 돌아갑니다.
    runs-on: ${{ matrix.os }}

    steps:
      - name: Say Hello World on ${{ matrix.os }}
        shell: bash
        run: |
          echo "Hello World on ${{ matrix.os }} with ${{ matrix.nodejs }}"

      - name: Say Hello World on ${{ matrix.os }}
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          echo "Hello World on ${{ matrix.os }} with ${{ matrix.nodejs }}"
