name: "SWM GitHub Actions Basic"

on: push

jobs:
  first-job:
    name: "First Job"

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]

    # 각각의 matrix마다 job이 돌아갑니다.
    runs-on: ${{ matrix.os }}

    steps:
      - name: Say Hello World on ${{ matrix.os }}
        shell: bash
        run: |
          echo "Hello World on ${{ matrix.os }}"
