name: "SWM GitHub Actions Basic"

on: push

jobs:
  first-job:
    name: "First Job"
    # 각각의 matrix마다 job이 돌아갑니다.
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        shell: bash
        run: |
          echo "Hello World"

  second-job:
    name: "Second Job"
    needs:
      - "first-job"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        shell: bash
        run: |
          echo "Hello World"

  third-job:
    name: "Third Job"
    needs:
      - "first-job"
      - "second-job"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        shell: bash
        run: |
          echo "Hello World"
