# 호출시 이름을 기준으로 호출하기 때문에 작성해주어야 합니다.
name: "SWM Github Actions Basic"

on: push

env:
  GLOBAL_LEVEL: "This value comes from the GLOBAL level"

jobs:
  # 각 job마다 별개의 서버로 돌립니다. job들 사이에서는 무슨일이 일어나는지 모릅니다.
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      # step 하나하나가 한 개의 task
      - name: Set output value
        id: first
        shell: bash
        run: |
          swm_value1="This is the value for the first output"
          swm_value2="This is the value for the second output"

          # echo "::set-output name=swm1::$swm_value1"
          # echo "::set-output name=swm2::$swm_value2"

          echo "swm1=$swm_value1" >> $GITHUB_OUTPUT
          echo "swm2=$swm_value2" >> $GITHUB_OUTPUT

      - name: Get output value
        shell: pwsh
        run: |
          echo "Output value1 is: ${{ steps.first.outputs.swm1 }}"
          echo "Output value2 is: ${{ steps.first.outputs.swm2 }}"

