# 호출시 이름을 기준으로 호출하기 때문에 작성해주어야 합니다.
name: "SWM Github Actions Basic"

on: push

jobs:
  # 각 job마다 별개의 서버로 돌립니다. job들 사이에서는 무슨일이 일어나는지 모릅니다.
  first-job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      # step 하나하나가 한 개의 task
      - name: Say Hello World1
        shell: bash
        run: echo "Hello World From step1"

      - name: Say Hello World2
        shell: pwsh
        run: echo "Hello World From step2"
